name: NoarboxCore
version: '${project.version}'
main: projects.tovy.github.Main
api-version: '1.18'
commands:
 screenshare:
   aliases: ss
   permission: ss.staff.usage
 shulker:
   permission: shulker.player.usage
 warp:

 killeffects:
 togglestash:
 staffmode:
   permission: noarbox.staff.mode
   description: "Work of art"
   aliases: sm



# main permission will be noarbox.operator.usage

