name: NoarboxCore
version: '${project.version}'
main: projects.tovy.github.Main
api-version: '1.18'
commands:
 shulker:
   permission: shulker.use
 warp:



# main permission will be noarbox.operator.usage

